version: '3.8'
services:
  s1:
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - '9001:9001'
    volumes:
      - oss-data-1:/data
    networks:
      - laf_shared_network

  s2:
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    volumes:
      - oss-data-2:/data
    networks:
      - laf_shared_network

  s3:
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    volumes:
      - oss-data-3:/data
    networks:
      - laf_shared_network

  s4:
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    volumes:
      - oss-data-4:/data
    networks:
      - laf_shared_network

networks:
  laf_shared_network:
    external: true

volumes:
  oss-data-1:
  oss-data-2:
  oss-data-3:
  oss-data-4:
